package com.javi.personal.wallascala.extractor.wallapop.model

case class WallaItem(
                      id: String,
                      title: String,
                      description: String,
                      distance: Float,
                      images: Seq[WallaImage],
                      user: WallaUser,
                      flags: WallaFlags,
                      visibility_flags: WallaVisibilityFlags,
                      price: Float,
                      currency: String,
                      free_shipping: Boolean,
                      web_slug: String,
                      category_id: Int,
                      //shipping: WallaShipping,
                      supports_shipping: Boolean,
                      shipping_allowed: Boolean,
                      seller_id: String,
                      favorited: Boolean,
                      creation_date: Long,
                      modification_date: Long,
                      //location: WallaLocation,
                      //type_attributes
                      //taxonomy
                      //discount
                    ) {

  def toRawItem: WallapopRawItem = WallapopRawItem(
    id = id,
    title = title,
    description = description,
    distance = distance,
    images = images.map(_.original).mkString(","),
    user_id = user.id,
    user_micro_name = user.micro_name,
    user_image_original = user.image.original,
    user_image_xsmall = user.image.xsmall,
    user_image_small = user.image.small,
    user_image_large = user.image.large,
    user_image_medium = user.image.medium,
    user_image_xlarge = user.image.xlarge,
    user_image_original_width = user.image.original_width,
    user_image_original_height = user.image.original_height,
    user_online = user.online,
    user_kind = user.kind,
    flag_pending = flags.pending,
    flag_sold = flags.sold,
    flag_reserved = flags.reserved,
    flag_banned = flags.banned,
    flag_expired = flags.expired,
    flag_onhold = flags.onhold,
    visibility_flag_bumped = visibility_flags.bumped,
    visibility_flag_highlighted = visibility_flags.highlighted,
    visibility_flag_urgent = visibility_flags.urgent,
    visibility_flag_country_bumped = visibility_flags.country_bumped,
    visibility_flag_boosted = visibility_flags.boosted,
    price = price,
    currency = currency,
    free_shipping = free_shipping,
    web_slug = web_slug,
    category_id = category_id,
    supports_shipping = supports_shipping,
    shipping_allowed = shipping_allowed,
    seller_id = seller_id,
    favorited = favorited,
    creation_date = creation_date,
    modification_date = modification_date,
  )

}
