  name: Deploy to GitHub Packages

  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'temurin'

        - name: Execute tests
          run: mvn test

        - name: Set up Git credentials
          env:
            TOKEN_GITHUB_PACKAGES: ${{ secrets.TOKEN_GITHUB_PACKAGES }}
          run: |
            mkdir -p ~/.m2
            echo "<settings><servers><server><id>github</id><username>javierolmo</username><password>\${env.TOKEN_GITHUB_PACKAGES}</password></server></servers></settings>" > ~/.m2/settings.xml

        - name: Deploy to GitHub Packages
          env:
            TOKEN_GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
          run: mvn deploy -DskipTests=true -Dmaven.javadoc.skip=true -B

        - uses: bacongobbler/azure-blob-storage-upload@main
          with:
            source_dir: 'target'
            container_name: 'artifacts'
            connection_string: ${{ secrets.AZURE_BLOBSTORAGE_CONNECTION_STRING }}
            overwrite: 'true'
            extra_args: '--pattern *jar-with-dependencies.jar'
