name: Check pull request before merging

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Get PR version
        id: pr-version
        run: |
          VERSION=$(.github/scripts/get-pom-version.sh pom.xml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "PR version: $VERSION"

      - name: Get main version
        id: main-version
        run: |
          VERSION=$(git show main:pom.xml | grep -m 1 "^\s*<version>" | sed 's/.*<version>\(.*\)<\/version>.*/\1/' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Main version: $VERSION"

      - name: Validate semver format
        run: |
          .github/scripts/validate-semver.sh "${{ steps.pr-version.outputs.version }}"

      - name: Check version increment
        run: |
          .github/scripts/compare-versions.sh "${{ steps.main-version.outputs.version }}" "${{ steps.pr-version.outputs.version }}"

  build:
    runs-on: ubuntu-latest
    needs: check-version
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build jar with dependencies
        run: mvn package

